# Generated by Django 5.2.8 on 2026-06-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('todo', '0002_alter_task_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
